"""
XAI Engine Configuration
Centralized thresholds for all features (Tier 1 + Tier 2 + Tier 3)
Auto-generated by threshold_tuning.ipynb
"""

# ============================================================================
# ALL THRESHOLDS (TIER 1 + TIER 2 + TIER 3) - OPTIMIZED
# ============================================================================

THRESHOLDS = {
    # TIER 1: Essential Features
    'SENTIMENT_EXTREME': 0.65,
    'WORD_COUNT_MIN': 58,
    'WORD_COUNT_MAX': 200,
    'ADJ_NOUN_RATIO': 0.62,
    'FIRST_PERSON_RATIO': 0.048,
    
    # TIER 2: Important Features
    'SPAM_KEYWORD_MIN': 2,
    'CAPS_RATIO_MAX': 0.01,
    'EXCESSIVE_PUNCT_MIN': 1,
    'UNIQUENESS_RATIO_MIN': 0.79,
    
    # TIER 3: Advanced Features
    'FLESCH_MAX': 85,  # Flag if readability too high (fake-like simplicity)
    'DALE_CHALL_MAX':7.0,  # Flag if too simple vocabulary
    'BIGRAM_REPETITIVENESS_MIN': 0.9,  # Flag if too repetitive
    'COMMON_FAKE_NGRAMS_MIN': 3,  # Flag if >=2 common fake phrases
    'TFIDF_SIMILARITY_MAX': 0.4  # Flag if too similar to generic reviews
}


def load_config():
    """Return a copy of thresholds"""
    return THRESHOLDS.copy()


def update_thresholds(new_thresholds):
    """Update thresholds (used by threshold tuning)"""
    THRESHOLDS.update(new_thresholds)
