"""
XAI Engine Configuration
Centralized thresholds for all features (Tier 1 + Tier 2 + Tier 3)
Auto-generated by threshold_tuning.ipynb
"""

# ============================================================================
# ALL THRESHOLDS (TIER 1 + TIER 2 + TIER 3) - OPTIMIZED
# ============================================================================

THRESHOLDS = {
    # TIER 1: Essential Features
    'SENTIMENT_EXTREME': 0.8,
    'WORD_COUNT_MIN': 15,
    'WORD_COUNT_MAX': 200,
    'ADJ_NOUN_RATIO': 2.5,
    'FIRST_PERSON_RATIO': 0.15,
    
    # TIER 2: Important Features
    'SPAM_KEYWORD_MIN':2,
    'CAPS_RATIO_MAX': 0.2,
    'EXCESSIVE_PUNCT_MIN': 3,
    'UNIQUENESS_RATIO_MIN': 0.6,
    
    # TIER 3: Advanced Features
    'FLESCH_MAX': 85,  # Flag if readability too high (fake-like simplicity)
    'DALE_CHALL_MAX':8.0,  # Flag if too simple vocabulary
    'BIGRAM_REPETITIVENESS_MIN': 0.9,  # Flag if too repetitive
    'COMMON_FAKE_NGRAMS_MIN': 3,  # Flag if >=2 common fake phrases
    'TFIDF_SIMILARITY_MAX': 0.45  # Flag if too similar to generic reviews
}


def load_config():
    """Return a copy of thresholds"""
    return THRESHOLDS.copy()


def update_thresholds(new_thresholds):
    """Update thresholds (used by threshold tuning)"""
    THRESHOLDS.update(new_thresholds)
