"""
XAI Engine Configuration
Centralized thresholds for all features (Tier 1 + Tier 2)
Auto-generated by threshold_tuning.ipynb
"""

# ============================================================================
# ALL THRESHOLDS (TIER 1 + TIER 2) - OPTIMIZED
# ============================================================================

THRESHOLDS = {
    # TIER 1: Essential Features
    'SENTIMENT_EXTREME': 0.95,
    'WORD_COUNT_MIN': 20,
    'WORD_COUNT_MAX': 200,
    'ADJ_NOUN_RATIO': 2.0,
    'FIRST_PERSON_RATIO': 0.1,
    
    # TIER 2: Important Features
    'SPAM_KEYWORD_MIN': 3,
    'CAPS_RATIO_MAX': 0.2,
    'EXCESSIVE_PUNCT_MIN': 3,
    'UNIQUENESS_RATIO_MIN': 0.6
}


def load_config():
    """Return a copy of thresholds"""
    return THRESHOLDS.copy()


def update_thresholds(new_thresholds):
    """Update thresholds (used by threshold tuning)"""
    THRESHOLDS.update(new_thresholds)
